<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <title>Procode test</title>
</head>
<body>
    <h1><?= $messages->get('books_list') ;?></h1>
    <?php if (!empty($books)) : ?>
        <ul>
            <?php foreach ($books as $book) : ?>
                <li>
                    <a href="/book/<?= $book['id']; ?>"><?= $book['name']; ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        <?= $messages->get('books_not_found') ;?>
    <?php endif; ?>
    <div>
        <h2><?= $messages->get('choosing_language') ;?></h2>
        <ul>
            <?php foreach ($languages as $lang) : ?>
                <li>
                    <a href="/lang/<?= $lang['id']; ?>"><?= $lang['id']; ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</body>
</html>
