<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <title>Procode test</title>
</head>
<body>
    <h1>Список книг</h1>
    <?php if (!empty($books)) : ?>
        <ul>
            <?php foreach ($books as $book) : ?>
                <li>
                    <a href="/book/<?= $book['id']; ?>"><?= $book['name']; ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        Книги не найдены
    <?php endif; ?>
    <div>
        <h2>Выбрите язык</h2>
        <ul>
            <?php foreach ($languages as $lang) : ?>
                <li>
                    <a href="/lang/<?= $lang['id']; ?>"><?= $lang['id']; ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</body>
</html>
