<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <title><?= $book['name'] ?></title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"><?= $messages->get('main'); ?></a></li>
                <li class="active"><a href="/book/<?= $book['id']; ?>"><?= $book['name'] ?></a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $page['content']; ?>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <?php if ($pagePagination->isFirst()) : ?>
                    <span><?= $messages->get('first_page'); ?></span>
                <?php else : ?>
                    <a href="/book/<?= $book['id']; ?>/1"><?= $messages->get('first_page'); ?></a>
                <?php endif; ?>
            </li>
            <?php foreach ($pagePagination->getPages() as $page) : ?>
                <li>
                    <?php if ($pagePagination->isCurrent($page)) : ?>
                        <span><?= $page; ?></span>
                    <?php else : ?>
                        <a href="/book/<?= $book['id']; ?>/<?= $page ;?>"><?= $page; ?></a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <li>
                <?php if ($pagePagination->isLast()) : ?>
                    <span><?= $messages->get('last_page'); ?></span>
                <?php else : ?>
                    <a href="/book/<?= $book['id']; ?>/<?= $pagePagination->getLast() ;?>"><?= $messages->get('last_page'); ?></a>
                <?php endif; ?>
            </li>
        </ul>
    </nav>
</div>


</body>
</html>